# Generated by Django 5.2.13 on 2026-07-18 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "domain",
                    models.CharField(
                        help_text="Email domain for auto-org-detection (e.g. acme.com)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrgSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fuel_cost_per_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Cost per km in org currency",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "max_search_radius_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Max pickup radius in km for ride search",
                        max_digits=6,
                    ),
                ),
                (
                    "booking_cutoff_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minutes before departure after which booking is closed",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
