# Generated by Django 5.2.13 on 2026-07-18 09:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pickup_label", models.CharField(max_length=255)),
                ("pickup_lat", models.FloatField()),
                ("pickup_lng", models.FloatField()),
                ("destination_label", models.CharField(max_length=255)),
                ("destination_lat", models.FloatField()),
                ("destination_lng", models.FloatField()),
                ("departure_datetime", models.DateTimeField()),
                ("seats_total", models.PositiveSmallIntegerField()),
                ("seats_available", models.PositiveSmallIntegerField()),
                ("fare_per_seat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=5,
                        help_text="Repeat for next N weekdays",
                        null=True,
                    ),
                ),
                ("route_geometry", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FULL", "Full"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["departure_datetime"],
            },
        ),
    ]
