# Generated by Django 6.0.4 on 2026-07-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TWO', 'Two-Wheeler'), ('THREE', 'Three-Wheeler'), ('FOUR', 'Four-Wheeler')], default='FOUR', max_length=10),
        ),
    ]
