# Generated by Django 6.0.4 on 2026-07-18 15:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0002_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=5),
        ),
    ]
