# Generated by Django 6.0.4 on 2026-07-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0003_ride_price_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='razorpay_key_id',
            field=models.CharField(default='rzp_test_mockkeyid123', max_length=100),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='razorpay_key_secret',
            field=models.CharField(default='mocksecret1234567890abcdef', max_length=100),
        ),
    ]
