# Generated by Django 6.0.4 on 2026-07-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_commute_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
