# Generated by Django 6.0.4 on 2026-07-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0006_employee_daily_commute_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
