# Generated by Django 6.0.4 on 2026-07-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0009_riderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
