# Generated by Django 6.0.4 on 2026-07-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0010_notification_target_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
