# Generated by Django 6.0.4 on 2026-07-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0011_trip_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'Wallet Balance'), ('UPI', 'UPI Payment')], default='WALLET', max_length=15),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'Wallet Balance'), ('UPI', 'UPI Payment')], default='WALLET', max_length=15),
        ),
    ]
